package com.example.YAPO.models.enums;

public enum ErrorList {
    WRONG_FIELD_TO_UPDATE,
    ERROR_DURING_DATABASE_SAVING,
    LOCALIZATION_NOT_FOUND,
    USER_NOT_FOUND,
    PLANT_NOT_FOUND,
    COMMENT_NOT_FOUND,
    PHOTO_NOT_FOUND,
    USERNAME_OR_EMAIL_ALREADY_IN_USE,
    UNEXPECTED_ERROR_DURING_DELETE,
    VALIDATION_ERROR,
    ERROR_DURING_SENDING_MAIL,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
}
